const API='https://script.google.com/macros/s/AKfycbxiBZgw7zebOv_V1h7Xvt_7fTDxZUQUyPsN5Wk9ysb4CClOhSveLUONxq0pyE6wvQXN/exec';
const MAX=30, colors=['#17214c','#6d3fd6','#087b9b','#e05220','#08785c','#1761d2','#d62976'];
const sig=document.getElementById('sig'),s=sig.getContext('2d'),wall=document.getElementById('wall'),w=wall.getContext('2d');
const nameEl=document.getElementById('name'),clearBtn=document.getElementById('clear'),addBtn=document.getElementById('add'),countEl=document.getElementById('count'),inksEl=document.getElementById('inks'),statusEl=document.getElementById('status');
let selectedInk=colors[0],marks=[],drawing=false,ink=false,last=null,strokes=[],activeStroke=null;
colors.forEach((c,i)=>{const b=document.createElement('button');b.className='ink'+(i?'':' selected');b.style.background=c;b.type='button';b.onclick=()=>{selectedInk=c;document.querySelectorAll('.ink').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');s.strokeStyle=c};inksEl.appendChild(b)});
function setupSig(){const r=sig.getBoundingClientRect(),d=Math.max(1,devicePixelRatio||1);sig.width=r.width*d;sig.height=r.height*d;s.setTransform(d,0,0,d,0,0);s.lineWidth=3;s.lineCap='round';s.lineJoin='round';s.strokeStyle=selectedInk}setupSig();
function pt(e){const r=sig.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top,w:r.width,h:r.height}}
function norm(p){return{x:Math.max(0,Math.min(1,p.x/p.w)),y:Math.max(0,Math.min(1,p.y/p.h))}}
sig.addEventListener('pointerdown',e=>{e.preventDefault();drawing=ink=true;last=pt(e);activeStroke=[norm(last)];strokes.push(activeStroke);try{sig.setPointerCapture(e.pointerId)}catch(_){}} ,{passive:false});
sig.addEventListener('pointermove',e=>{if(!drawing)return;e.preventDefault();const q=pt(e);s.beginPath();s.moveTo(last.x,last.y);s.lineTo(q.x,q.y);s.stroke();last=q;activeStroke.push(norm(q))},{passive:false});
['pointerup','pointercancel'].forEach(evt=>sig.addEventListener(evt,e=>{e.preventDefault();drawing=false;activeStroke=null},{passive:false}));
function clearSig(){s.clearRect(0,0,sig.width,sig.height);ink=false;strokes=[];activeStroke=null}clearBtn.onclick=clearSig;
const slots=[[150,120],[430,105],[720,135],[1030,100],[1320,130],[1620,110],[210,275],[520,245],[780,290],[1110,250],[1430,285],[1660,260],[170,455],[410,520],[1400,455],[1640,515],[145,690],[390,650],[1410,675],[1650,635],[170,870],[440,830],[710,900],[1080,855],[1360,900],[1620,850],[300,1050],[650,1015],[1190,1045],[1540,1020]];
function hash(str){let h=2166136261;for(const ch of str){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}function rand(seed){let t=seed+0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}
function base(){w.fillStyle='#f8f3e9';w.fillRect(0,0,1800,1200);w.textAlign='center';w.fillStyle='#171b3d';w.font='900 118px Arial';w.fillText('INF 125',900,535);w.font='900 94px Arial';w.fillText('AI LITERACY',900,639);w.font='italic 43px Georgia';w.fillText('Curious People. Build Brighter Futures.',900,708);w.strokeStyle='#6d3fd6';w.lineWidth=8;w.beginPath();w.moveTo(690,745);w.quadraticCurveTo(900,705,1120,738);w.stroke();w.textAlign='left';w.font='700 22px Arial';w.fillText('DIFFERENT PEOPLE.',70,1115);w.fillText('SHARED JOURNEY.',70,1145);w.fillText('LASTING IMPACT.',70,1175);w.textAlign='right';w.font='800 34px Arial';w.fillText('NKU  |  FALL 2026',1730,1145)}
function bounds(st){let minX=1,minY=1,maxX=0,maxY=0;st.flat().forEach(p=>{minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x);maxY=Math.max(maxY,p.y)});return{minX,minY,w:Math.max(.05,maxX-minX),h:Math.max(.05,maxY-minY)}}
function drawMark(m,i){if(!m.strokes?.length)return;const [cx,cy]=slots[i],b=bounds(m.strokes),aspect=b.w/b.h,seed=hash((m.name||'mark')+i),scale=.82+rand(seed+33)*.55;let dw=Math.min(300,Math.max(150,aspect*88))*scale,dh=dw/aspect;if(dh>135){dh=135;dw=dh*aspect}w.save();w.translate(cx+(rand(seed)-.5)*34,cy+(rand(seed+9)-.5)*32);w.rotate((-9+rand(seed+27)*18)*Math.PI/180);w.strokeStyle=m.color||'#17214c';w.lineWidth=6;w.lineCap='round';w.lineJoin='round';for(const line of m.strokes){w.beginPath();line.forEach((p,j)=>{const x=((p.x-b.minX)/b.w-.5)*dw,y=((p.y-b.minY)/b.h-.5)*dh;j?w.lineTo(x,y):w.moveTo(x,y)});w.stroke()}w.restore()}
function render(){base();marks.slice(0,MAX).forEach(drawMark);countEl.textContent=marks.length}
async function loadShared(){try{const r=await fetch(API+'?action=list&_='+Date.now(),{cache:'no-store'}),data=await r.json();if(!data.ok)throw Error(data.error||'Load failed');marks=data.signatures||[];render();statusEl.textContent='Shared wall connected · '+marks.length+' signatures';statusEl.className='status ok'}catch(e){statusEl.textContent='Shared wall connection failed: '+e.message;statusEl.className='status err'}}
addBtn.onclick=async()=>{if(marks.length>=MAX)return alert('The wall is full.');const name=nameEl.value.trim();if(!name)return alert('Add your name first.');if(!ink||!strokes.length)return alert('Draw your mark first.');addBtn.disabled=true;addBtn.textContent='Adding…';try{const body=new URLSearchParams({action:'submit',name,color:selectedInk,strokes:JSON.stringify(strokes)});const r=await fetch(API,{method:'POST',body}),data=await r.json();if(!data.ok)throw Error(data.error||'Submit failed');nameEl.value='';clearSig();await loadShared();alert('Your mark is now part of the INF 125 wall. ✨')}catch(e){alert('Your mark was not saved: '+e.message)}finally{addBtn.disabled=false;addBtn.textContent='✎ Add My Signature'}};
render();loadShared();setInterval(loadShared,5000);